"""add tables insert combo in pedido

Revision ID: 05d03be64fa6
Revises: 7c952ee6673f
Create Date: 2024-06-05 13:39:46.802281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05d03be64fa6'
down_revision: Union[str, None] = '7c952ee6673f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caixas', 'data_fechamento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('caixas', 'saldo_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transacoes', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacoes', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('caixas', 'saldo_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('caixas', 'data_fechamento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
