"""remove created_at to categoria

Revision ID: 17cf7f8ffc44
Revises: a48a3ca8271b
Create Date: 2024-05-27 03:33:32.614480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17cf7f8ffc44'
down_revision: Union[str, None] = 'a48a3ca8271b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'created_usr')
    op.drop_column('categorias', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('categorias', sa.Column('created_usr', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
