"""add field observacao to pedido

Revision ID: 1a53fdc9de2f
Revises: 2a425d6c8573
Create Date: 2024-06-09 05:21:24.962299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a53fdc9de2f'
down_revision: Union[str, None] = '2a425d6c8573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('observacao', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'observacao')
    # ### end Alembic commands ###
