"""correct fields to insert pedido_combo

Revision ID: 2a425d6c8573
Revises: 0a5c92425db0
Create Date: 2024-06-08 03:56:25.606581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a425d6c8573'
down_revision: Union[str, None] = '0a5c92425db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combos', sa.Column('quantidade_espeto', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combos', 'quantidade_espeto')
    # ### end Alembic commands ###
