"""add tables caixas and transacoes

Revision ID: 4075b82f2321
Revises: a8eb2e589472
Create Date: 2024-06-04 03:29:03.232567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4075b82f2321'
down_revision: Union[str, None] = 'a8eb2e589472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=False),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('saldo_final', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo_transacao', sa.Enum('Entrada', 'Saída', name='tipo_transacao_enum'), nullable=False),
    sa.Column('tipo_pagamento', sa.Enum('Dinheiro', 'CartaoCredito', 'CartaoDebito', 'Pix', 'TransferenciaBancaria', 'Outros', name='tipo_pagamento_enum'), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('caixa_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes')
    op.drop_table('caixas')
    # ### end Alembic commands ###
