"""adjust table pedidos and transacao

Revision ID: 7c952ee6673f
Revises: 4075b82f2321
Create Date: 2024-06-04 14:08:10.393878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c952ee6673f'
down_revision: Union[str, None] = '4075b82f2321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
