"""add relationship produtos in categoria

Revision ID: 8e895763969f
Revises: f1c4e9e258c6
Create Date: 2024-05-26 20:47:07.082970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e895763969f'
down_revision: Union[str, None] = 'f1c4e9e258c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
