"""add movimentacao_estoque table

Revision ID: a5fd2c5a2add
Revises: eec23b11767f
Create Date: 2024-06-16 14:30:23.592793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5fd2c5a2add'
down_revision: Union[str, None] = 'eec23b11767f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('preco_custo', sa.Float(), nullable=False))
    op.add_column('produtos', sa.Column('preco_venda', sa.Float(), nullable=False))
    op.add_column('produtos', sa.Column('medida', sa.String(length=2), nullable=False))
    op.add_column('produtos', sa.Column('estoque_minimo', sa.Integer(), nullable=False))
    op.add_column('produtos', sa.Column('estoque_atual', sa.Integer(), nullable=False))
    op.drop_column('produtos', 'preco')
    op.drop_column('produtos', 'estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('produtos', 'estoque_atual')
    op.drop_column('produtos', 'estoque_minimo')
    op.drop_column('produtos', 'medida')
    op.drop_column('produtos', 'preco_venda')
    op.drop_column('produtos', 'preco_custo')
    # ### end Alembic commands ###
