"""add nulllable true in tables

Revision ID: a8eb2e589472
Revises: 17cf7f8ffc44
Create Date: 2024-05-27 03:44:00.848950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8eb2e589472'
down_revision: Union[str, None] = '17cf7f8ffc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pedidos', 'updated_usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pedidos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('produtos', 'foto_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('produtos', 'updated_usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produtos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('produtos', 'updated_usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('produtos', 'foto_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('pedidos', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pedidos', 'updated_usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
