"""add mapper to usuarios table #5

Revision ID: b9dcb4a55a19
Revises: a28ec6b0f236
Create Date: 2024-05-26 21:19:47.225830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9dcb4a55a19'
down_revision: Union[str, None] = 'a28ec6b0f236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
