"""add movimentacao_estoque table 2

Revision ID: db325ccf09af
Revises: a5fd2c5a2add
Create Date: 2024-06-16 14:38:10.586831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db325ccf09af'
down_revision: Union[str, None] = 'a5fd2c5a2add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=20), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes_estoque')
    # ### end Alembic commands ###
