"""add default fields; add usuarios table

Revision ID: f1c4e9e258c6
Revises: eee3e433b44f
Create Date: 2024-05-26 20:26:45.525068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c4e9e258c6'
down_revision: Union[str, None] = 'eee3e433b44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pedidos', sa.Column('emissao', sa.DateTime(), nullable=False))
    op.add_column('pedidos', sa.Column('created_usuario_id', sa.Integer(), nullable=False))
    op.add_column('pedidos', sa.Column('updated_usuario_id', sa.Integer(), nullable=False))
    op.add_column('pedidos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('pedidos', 'status',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['updated_usuario_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['created_usuario_id'], ['id'])
    op.drop_column('pedidos', 'data')
    op.drop_column('pedidos', 'created_usr')
    op.add_column('produtos', sa.Column('created_usuario_id', sa.Integer(), nullable=False))
    op.add_column('produtos', sa.Column('updated_usuario_id', sa.Integer(), nullable=False))
    op.add_column('produtos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'produtos', 'usuarios', ['created_usuario_id'], ['id'])
    op.create_foreign_key(None, 'produtos', 'usuarios', ['updated_usuario_id'], ['id'])
    op.drop_column('produtos', 'created_usr')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('created_usr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'updated_at')
    op.drop_column('produtos', 'updated_usuario_id')
    op.drop_column('produtos', 'created_usuario_id')
    op.add_column('pedidos', sa.Column('created_usr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pedidos', sa.Column('data', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.alter_column('pedidos', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('pedidos', 'updated_at')
    op.drop_column('pedidos', 'updated_usuario_id')
    op.drop_column('pedidos', 'created_usuario_id')
    op.drop_column('pedidos', 'emissao')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
